//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositoryTest.Models
{
    using System;
    
    public partial class GetEmp_Result3
    {
        public Nullable<int> EmpId { get; set; }
        public string EmpName { get; set; }
        public string EmpAlias1 { get; set; }
        public string EmpAlias2 { get; set; }
        public string EmpAlias3 { get; set; }
    }
}
